version: '3.9'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - 8001:80
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./.docker/web/nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/magnetar
  php-fpm:
    build:
      context: ./.docker/php-fpm
      dockerfile: Dockerfile
    restart: always
    stop_grace_period: 1s
    volumes:
      - ./.docker/php-fpm/ini-overrides.ini:/usr/local/etc/php/conf.d/99-zzzoverrides.ini:ro
      - ./:/magnetar
    env_file:
      - ./.docker/.env
    environment:
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      DB_HOST: "${COMPOSE_PROJECT_NAME}-mariadb-1"
      CACHE_HOST: "${COMPOSE_PROJECT_NAME}-memcached-1"
    ports:
      #- 9000:9000
      - 9003:9003
    depends_on:
      - mariadb
      - memcached
    links:
      - mariadb
      - memcached
  mariadb:
    image: mariadb
    restart: always
    env_file:
      - ./.docker/mariadb/.env
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
  memcached:
    image: memcached:latest
    restart: always